### ISSUE TITLE
pipx install broken?

### ISSUE THREAD

**Issue by idoru** [atmandhol/sup#1]
```
❯ pipx reinstall sup
uninstalled sup! ✨ 🌟 ✨
  installed package sup 0.1.0, installed using Python 3.12.3
  These apps are now globally available
    - sup
done! ✨ 🌟 ✨

❯ sup
Traceback (most recent call last):
  File "/Users/scoward/.local/bin/sup", line 5, in <module>
    from sup.main import app
  File "/Users/scoward/.local/pipx/venvs/sup/lib/python3.12/site-packages/sup/main.py", line 4, in <module>
    from widgets.run_list import RunList
ModuleNotFoundError: No module named 'widgets'
```

**Comment by atmandhol** [comment]
Fixed on https://github.com/atmandhol/sup/commit/98f32095c4fc4c16d1f9df62cc8cf6541ea64b53
